# Project information
site_name: Piston-CLI
site_description: Piston CLI, a universal shell supporting code highlighting, files, and interpretation without the need to download a language.
site_url: https://shivansh-007.github.io/piston-cli/

# Repository
repo_name: Shivansh-007/piston-cli/
repo_url: https://github.com/Shivansh-007/piston-cli/
edit_uri: "edit/main/docs/"

# Copyright
copyright: Copyright &copy; 2021 Shivansh-007

# Dev Configuration
dev_addr: 127.0.0.1:8008

# Configuration
theme:
  name: material
  locale: en

  # Colorscheme for the docs
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue
    accent: purple
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

  # Enabled mkdocs features for the site
  features:
  - navigation.top
  - navigation.instant
  - search.suggest
  - search.highlight
  icon:
    repo: fontawesome/brands/github-alt
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: en

# Plugins
plugins:
- search
- markdownextradata:
    data: data

# Page tree
nav:
- Home: index.md

# Extensions
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_div_format ''
- pymdownx.tabbed

# Customization
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/Piston-CLI/piston-cli
  - icon: fontawesome/brands/discord
    link: https://discord.gg/c7dZ4zdGQT

# Custom css for the site
extra_css:
- css/termynal.css
- css/custom.css

# Custom javascript for the site
extra_javascript:
- https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
- js/termynal.js
- js/custom.js
