name: Upload Python Package

on:
  release:
    types: [created]
jobs:
  publish_pypi_package:
    name: Build & Publish PyPI package
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies using poetry
        run: |
          pip install poetry
          poetry install --no-interaction --no-ansi
      - name: Build package using poetry
        run: poetry build

      - name: Publish package with Poetry
        run: poetry publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
